### 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np

# create null vector of size 10
null_vector = np.zeros(10)

# set the fifth value to 1
null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. Create a vector with values ranging from 10 to 49.

In [2]:
import numpy as np

# create a vector with values ranging from 10 to 49
my_vector = np.arange(10, 50)

print(my_vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
import numpy as np

# create a 3x3 matrix with values ranging from 0 to 8
my_matrix = np.arange(9).reshape(3, 3)

print(my_matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
import numpy as np

# create the input array
my_array = np.array([1, 2, 0, 0, 4, 0])

# find the indices of non-zero elements
nonzero_indices = np.nonzero(my_array)

print(nonzero_indices)


(array([0, 1, 4], dtype=int64),)


### 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [9]:
import numpy as np

# create a 10x10 array with random values
my_array = np.random.rand(10, 10)

# find the minimum and maximum values
min_value = my_array.min()
max_value = my_array.max()

print("Minimum value:", min_value)
print("Maximum value:", max_value)


Minimum value: 0.014207284964959488
Maximum value: 0.9850071515068444


### 6. Create a random vector of size 30 and find the mean value.


In [10]:
import numpy as np

# create a random vector of size 30
my_vector = np.random.rand(30)

# find the mean value
mean_value = np.mean(my_vector)

print("Mean value:", mean_value)


Mean value: 0.5020821848012323
